matrix:
  include:
    - language: erlang

      before_install:
        - cd server

      install:
        - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

      otp_release:
        - 21.0
        - 20.2
        - 20.1
        - 20.0
        - 19.3
        - 19.2
        - 19.1

      script:
        - ./rebar3 compile
        - ./rebar3 eunit

    - language: node_js

      before_script:
        - cd client

      script:
        - yarn build

# vim: et sw=2 sts=2:
