matrix:
  include:
    - language: erlang

      before_install:
        - cd server

      install:
        - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

      otp_release:
        - 19.3

      script:
        - ./rebar3 compile
        - ./rebar3 eunit
        - ./rebar3 dialyzer

    - language: erlang

      before_install:
        - cd server

      install:
        - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

      otp_release:
        - 21.0

      script:
        - ./rebar3 compile
        - ./rebar3 eunit
        - ./rebar3 dialyzer

    - language: erlang

      before_install:
        - cd server

      install:
        - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

      otp_release:
        - 20.3

      script:
        - ./rebar3 compile
        - ./rebar3 eunit
        - ./rebar3 dialyzer

    - language: node_js

      node_js:
        - "8.11.3"

      before_install:
        # this is necessary to build in < 10 min
        # see: <https://github.com/elm-lang/elm-compiler/issues/1473>
        - git clone https://github.com/obmarg/libsysconfcpus.git
        - cd libsysconfcpus
        - ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus
        - make && make install
        - cd ../client

      install:
        - yarn

      script:
        - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn build

    - language: node_js

      node_js:
        - "10.7.0"

      before_install:
        # this is necessary to build in < 10 min
        # see: <https://github.com/elm-lang/elm-compiler/issues/1473>
        - git clone https://github.com/obmarg/libsysconfcpus.git
        - cd libsysconfcpus
        - ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus
        - make && make install
        - cd ../client

      install:
        - yarn

      script:
        - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 yarn build

sudo: false

# vim: et sw=2 sts=2:
